version: '3.8'
services:
  express_app:
    container_name: express_app
    image: chiyotori/express_app:latest
    ports:
      - 5000:5000

  watchtower:
    image: containrrr/watchtower
    environment:
      -  WATCHTOWER_POLL_INTERVAL=60 # Poll every 60 seconds
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower