name: Release Node.js app

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3

        # We need to login so we can later push the image without issues.
        - name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        # Builds devopsdockeruh/docker-hy.github.io
        - name: Build and push
          uses: docker/build-push-action@v3
          with:
            context: .
            file: Dockerfile
            push: true
            tags: chiyotori/express_app:latest
